spring.application.name=Backend_Securify
spring.jpa.database=postgresql
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost/securify_db
spring.datasource.username=postgres
spring.datasource.password=vane


#No envia el trace al usuario cuando hay error.
server.error.include-stacktrace=never
#spring.jackson.date-format=yyyy-dd-MM

ip.frontend=http://localhost:4200

jwt.secret=miClaveSuperSegura123456789


