spring.application.name=Backend_Securify
spring.jpa.database=postgresql
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost/securify_db
spring.datasource.username=postgres
spring.datasource.password=Postgres2025
ip.frontend=http://localhost:4200
